stages:
  - UAT_deployment

deploy_to_uat:
  image: openjdk:17-slim
  stage: UAT_deployment
  before_script:
    - apt-get update
    - apt-get install -y wget default-jdk unzip xz-utils
    - wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
    - mkdir -p ~/cli/sf
    - tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
    - export PATH="$HOME/cli/sf/bin:$PATH"
    - sf version
    - |
      if [ "$CI_COMMIT_BRANCH" == "UAT-Branch" ]; then
        echo "Authenticating in UAT sandbox..."
        sf login org jwt --alias deployOrg \
          --client-id $SF_CLIENT_ID \
          --jwt-key-file accesskey/server.key \
          --set-default \
          --instance-url https://test.salesforce.com \
          --username $SF_USERNAME
        echo "Authenticated in UAT sandbox."
      fi
  script:
    - echo "Deployment started ..."
    - sf project deploy start -x manifest/package.xml --target-org deployOrg --test-level RunSpecifiedTests --tests "$TEST_CLASSES" --ignore-warnings --verbose
    - echo "Deployment Finished."
  rules:
    - if: '$CI_COMMIT_BRANCH == "UAT-Branch"'
